version: 2

.build_template: &build_definition
  steps:
    - checkout
    - run: bundle install
    - run: bundle exec rake
  working_directory: ~/app

jobs:
  build:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  build_ruby2_4:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  build_ruby2_3:
    <<: *build_definition
    docker:
      - image: ruby:2.3

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build
      - build_ruby2_4
      - build_ruby2_3
